### PR TITLE
Add scoping option to AuthnRequest

### PR DESCRIPTION
**Pull request by Ricky-rick**
Add scoping to  a service provider to specify a list of identity providers in an authnRequest to a proxying identity provider.
Fix Issue #211 

Travis fails on pdepend wich has no relation with this PR
`PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in /home/travis/build/onelogin/php-saml/tests/ZendModStandard/Sniffs/Debug/CodeAnalyzerSniff.php on line 30`

### CODE REVIEW

**Comment by Ricky-rick** [comment]
I updated the pull request so it has no conflicts with the master branch.
Can you merge the pr or give me a hint on how to solve the issue?

**Comment by stayallive** [comment]
I would go for maintaining a fork with this patched in since I don't think it will be accepted.

Reference: onelogin/php-saml#137

**Comment by arnoudhgz** [comment]
I would really like this feature. 
It does not really make it more difficult for users to use this package. If they don't know the feature, they don't care.

**Comment by pitbulk** [comment]
Not official support for it.

**Pull request closed without merging**
