### PR TITLE
Add support for encrypted name id in encrypted assertion

### PR DESCRIPTION
**Pull request by joonlabs**
Hey @pitbulk,

this is the PR for the issue #318. I added a check for the existence of an `EncryptedID` element during the decryption of the assertion. If it exists, the same method can be called recursively to decrypt the encrypted name id.
I also removed the validation error, that throws when an encrypted name id is detected in an encrypted assertion, since this is supported with this PR.
I added a signed SAML response with encrypted assertion that contains an encrypted name id to the test data and wrote a test case to ensure the validation of the response and the correct retrieving of the name id.

Let me know if that works for you, or you miss anything.

Best 
Julius

### CODE REVIEW

**Comment by pitbulk** [comment]
Can yo fix the lint error?

**Comment by joonlabs** [comment]
Hey @pitbulk,

I saw the run failed due to PHP Sniffer. I use a different intended / formatting tool at my IDEA. I'll fix the 'if' statement and request again.
Is there a way for me to check the rest of the pipeline by myself before I commit? 

Best
Julius

**Comment by joonlabs** [comment]
@pitbulk fixed the lint error. Please allow the workflow to run again.

**Comment by joonlabs** [comment]
@pitbulk quick check in, could you please run the workflow again and merge the pull request if successful? 

Best
Julius

**Comment by joonlabs** [comment]
@pitbulk thank you for merging. When will this be included in a release?

**Comment by joonlabs** [comment]
Hi @pitbulk. I just wanted to ask if you see the possibility to create a new release? We need to incorporate this feature into our software as our clients are waiting for a new SAML Idp we only can connect with this feature merge. We would love to use a stable version of this library and don't want to integrate the dev branch. Happy to hear from you,
Julius :D

**Comment by joonlabs** [comment]
@pitbulk any news on this?

**Pull request merged**
